/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Test_Project;

import Test_Project.Models.Branch;
import Test_Project.Models.Campus;
import Test_Project.Models.CampusCareer;
import Test_Project.Models.Career;
import Test_Project.Models.University;
import Test_Project.Utils.DBConnection;
import Test_Project.Utils.JsonDataFetcher;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            University test = JsonDataFetcher.fetchTableData(
                University.getTABLENAME(),
                "id_university = 6",
                University.class);
            System.out.println("ID" + test.getIdUniversity());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
